<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlacementQuestionSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [
            [
                'language' => 'ingles',
                'level' => 'A1',
                'category' => 'vocabulario',
                'question' => '¿Qué significa “Hello”?',
                'options' => json_encode([
                    'Adiós',
                    'Hola',
                    'Gracias',
                    'Por favor',
                ]),
                'correct_answer' => 1,
                'explanation' => 'Hello significa Hola.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A1',
                'category' => 'gramatica',
                'question' => 'Completa: “I ___ a student”.',
                'options' => json_encode([
                    'am',
                    'is',
                    'are',
                    'be',
                ]),
                'correct_answer' => 0,
                'explanation' => 'Con I se utiliza am.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A1',
                'category' => 'vocabulario',
                'question' => '¿Qué significa “Good morning”?',
                'options' => json_encode([
                    'Buenas noches',
                    'Buenos días',
                    'Hasta luego',
                    'Bienvenido',
                ]),
                'correct_answer' => 1,
                'explanation' => 'Good morning significa Buenos días.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A1',
                'category' => 'vocabulario',
                'question' => '¿Qué significa “Thank you”?',
                'options' => json_encode(['Hola', 'Gracias', 'Adiós', 'Perdón']),
                'correct_answer' => 1,
                'explanation' => 'Thank you significa Gracias.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A1',
                'category' => 'gramatica',
                'question' => 'Completa: “They ___ friends”.',
                'options' => json_encode(['am', 'is', 'are', 'be']),
                'correct_answer' => 2,
                'explanation' => 'Con They se utiliza are.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A1',
                'category' => 'vocabulario',
                'question' => '¿Qué significa “Book”?',
                'options' => json_encode(['Mesa', 'Libro', 'Silla', 'Puerta']),
                'correct_answer' => 1,
                'explanation' => 'Book significa Libro.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A1',
                'category' => 'gramatica',
                'question' => 'Completa: “This ___ my house”.',
                'options' => json_encode(['am', 'are', 'is', 'be']),
                'correct_answer' => 2,
                'explanation' => 'Con This se utiliza is.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A1',
                'category' => 'vocabulario',
                'question' => '¿Qué significa “Water”?',
                'options' => json_encode(['Agua', 'Comida', 'Leche', 'Pan']),
                'correct_answer' => 0,
                'explanation' => 'Water significa Agua.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A1',
                'category' => 'gramatica',
                'question' => 'Selecciona la opción correcta: “She ___ happy”.',
                'options' => json_encode(['am', 'are', 'is', 'be']),
                'correct_answer' => 2,
                'explanation' => 'Con She se utiliza is.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A1',
                'category' => 'vocabulario',
                'question' => '¿Qué significa “Red”?',
                'options' => json_encode(['Azul', 'Verde', 'Rojo', 'Amarillo']),
                'correct_answer' => 2,
                'explanation' => 'Red significa Rojo.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A1',
                'category' => 'comprension',
                'question' => '“My name is Ana”. ¿Qué significa?',
                'options' => json_encode([
                    'Mi nombre es Ana',
                    'Ana es mi amiga',
                    'Vivo con Ana',
                    'Conozco a Ana',
                ]),
                'correct_answer' => 0,
                'explanation' => 'My name is Ana significa Mi nombre es Ana.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
                ];

        $questions = array_merge($questions, [
            [
                'language' => 'ingles',
                'level' => 'A2',
                'category' => 'gramatica',
                'question' => 'Completa: “She ___ to work by bus”.',
                'options' => json_encode(['go', 'goes', 'going', 'gone']),
                'correct_answer' => 1,
                'explanation' => 'Con She se utiliza goes.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A2',
                'category' => 'gramatica',
                'question' => '¿Cuál es el pasado de “buy”?',
                'options' => json_encode(['Buyed', 'Bought', 'Buying', 'Buys']),
                'correct_answer' => 1,
                'explanation' => 'Bought es el pasado irregular de buy.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A2',
                'category' => 'vocabulario',
                'question' => '¿Qué significa “expensive”?',
                'options' => json_encode(['Barato', 'Rápido', 'Caro', 'Pequeño']),
                'correct_answer' => 2,
                'explanation' => 'Expensive significa caro.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A2',
                'category' => 'gramatica',
                'question' => 'Completa: “I have ___ finished my homework”.',
                'options' => json_encode(['yet', 'already', 'ever', 'never']),
                'correct_answer' => 1,
                'explanation' => 'Already se usa para indicar que algo ya ocurrió.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A2',
                'category' => 'comprension',
                'question' => '“Tom is taller than John”. ¿Qué significa?',
                'options' => json_encode([
                    'Tom es más bajo que John',
                    'Tom es más alto que John',
                    'John es más rápido que Tom',
                    'Tom y John tienen la misma altura',
                ]),
                'correct_answer' => 1,
                'explanation' => 'Taller than significa más alto que.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A2',
                'category' => 'gramatica',
                'question' => 'Completa: “There ___ any milk in the fridge”.',
                'options' => json_encode(['isn’t', 'aren’t', 'don’t', 'doesn’t']),
                'correct_answer' => 0,
                'explanation' => 'Milk es incontable, por eso se usa isn’t.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A2',
                'category' => 'vocabulario',
                'question' => '¿Qué significa “borrow”?',
                'options' => json_encode([
                    'Prestar algo',
                    'Tomar prestado',
                    'Comprar algo',
                    'Romper algo',
                ]),
                'correct_answer' => 1,
                'explanation' => 'Borrow significa tomar prestado.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A2',
                'category' => 'gramatica',
                'question' => 'Completa: “If it rains, I ___ at home”.',
                'options' => json_encode(['stay', 'stayed', 'staying', 'stays']),
                'correct_answer' => 0,
                'explanation' => 'En este caso se usa stay después de I.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A2',
                'category' => 'comprension',
                'question' => '“I have lived here for two years”. ¿Qué significa?',
                'options' => json_encode([
                    'Viví aquí hace dos años',
                    'Vivo aquí desde hace dos años',
                    'Viviré aquí dos años',
                    'No vivo aquí',
                ]),
                'correct_answer' => 1,
                'explanation' => 'La frase indica una acción que comenzó en el pasado y continúa.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A2',
                'category' => 'gramatica',
                'question' => 'Selecciona la opción correcta: “I ___ watch TV yesterday”.',
                'options' => json_encode([
                    'don’t',
                    'doesn’t',
                    'didn’t',
                    'not',
                ]),
                'correct_answer' => 2,
                'explanation' => 'Para negar en pasado se utiliza didn’t.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
                ]);

        $advancedQuestions = [
            ['B1', 'gramatica', 'If I had more time, I ___ another language.', ['learn', 'would learn', 'learned', 'will learn'], 1, 'The second conditional uses would plus the base verb.'],
            ['B1', 'comprension', '“She has been working here since 2022”. What does it mean?', ['She will work here in 2022', 'She started working here in 2022 and still does', 'She stopped working in 2022', 'She worked here once'], 1, 'The present perfect continuous connects a past action with the present.'],
            ['B1', 'vocabulario', 'What does “reliable” mean?', ['Easy to break', 'Able to be trusted', 'Very expensive', 'Difficult to find'], 1, 'Reliable means able to be trusted.'],
            ['B1', 'gramatica', 'Choose the correct option: “The book ___ by millions of people.”', ['has read', 'has been read', 'is reading', 'read'], 1, 'This is the present perfect passive.'],
            ['B1', 'vocabulario', 'What does “however” express?', ['Contrast', 'Time', 'Place', 'Permission'], 0, 'However introduces a contrast.'],
            ['B1', 'gramatica', '“I wish I ___ more free time.”', ['have', 'had', 'will have', 'am having'], 1, 'Wish about the present uses the past simple.'],
            ['B1', 'comprension', '“Despite the rain, we continued walking.” What does despite mean?', ['Because of', 'Although there was', 'Before', 'Instead of'], 1, 'Despite introduces a contrast.'],
            ['B1', 'gramatica', 'Complete: “You ___ have told me earlier.”', ['should', 'should to', 'must to', 'can to'], 0, 'Should is followed directly by the base verb.'],
            ['B1', 'vocabulario', 'What is the closest meaning of “improve”?', ['Get better', 'Get lost', 'Get smaller', 'Get colder'], 0, 'Improve means get better.'],
            ['B1', 'comprension', '“The meeting was put off until Friday.” What happened?', ['It was cancelled forever', 'It was moved to Friday', 'It started early', 'It became shorter'], 1, 'Put off means postponed.'],
            ['B2', 'gramatica', 'Had I known about the delay, I ___ earlier.', ['would leave', 'would have left', 'will leave', 'left'], 1, 'This is a third conditional inversion.'],
            ['B2', 'vocabulario', 'What does “thorough” mean?', ['Incomplete', 'Careful and detailed', 'Very quick', 'Unnecessary'], 1, 'Thorough means careful and detailed.'],
            ['B2', 'gramatica', 'Not only ___ late, but he also forgot the documents.', ['he arrived', 'did he arrive', 'he did arrive', 'arrived he'], 1, 'After Not only at the beginning, inversion is used.'],
            ['B2', 'comprension', '“The proposal is unlikely to be approved.” What does unlikely mean?', ['Certain to happen', 'Not expected to happen', 'Already approved', 'Easy to understand'], 1, 'Unlikely means not expected to happen.'],
            ['B2', 'vocabulario', 'What does “nevertheless” express?', ['Addition', 'Contrast', 'Cause', 'Sequence'], 1, 'Nevertheless introduces a contrast.'],
            ['B2', 'gramatica', 'The manager demanded that the report ___ rewritten.', ['is', 'be', 'was', 'being'], 1, 'After demand, the subjunctive uses the base form be.'],
            ['B2', 'comprension', '“The findings call into question the original theory.” What does this mean?', ['They strongly confirm it', 'They make its validity doubtful', 'They explain it clearly', 'They replace the findings'], 1, 'Call into question means make doubtful.'],
            ['B2', 'vocabulario', 'What does “feasible” mean?', ['Possible and practical', 'Extremely dangerous', 'Already completed', 'Impossible to measure'], 0, 'Feasible means possible and practical.'],
            ['B2', 'gramatica', 'Were it not for your help, I ___ the project.', ['could not have completed', 'cannot complete', 'will not complete', 'did not complete'], 0, 'Were it not for introduces a hypothetical condition.'],
            ['B2', 'comprension', '“The issue remains unresolved.” What does unresolved mean?', ['Solved completely', 'Not solved yet', 'Recently created', 'Widely discussed'], 1, 'Unresolved means not solved yet.'],

            ['C1', 'gramatica', 'By the time we arrived, the lecture ___.', ['had already started', 'already starts', 'has started', 'would start'], 0, 'The past perfect describes an action completed before another past action.'],
            ['C1', 'vocabulario', 'What does “meticulous” mean?', ['Careless', 'Extremely careful and precise', 'Very fast', 'Uncertain'], 1, 'Meticulous means extremely careful and precise.'],
            ['C1', 'comprension', '“The evidence was deemed insufficient.” What does deemed mean?', ['Destroyed', 'Considered', 'Hidden', 'Collected'], 1, 'Deemed means considered or judged to be.'],
            ['C1', 'gramatica', 'It is essential that every applicant ___ the form.', ['completes', 'complete', 'completed', 'completing'], 1, 'After It is essential that, formal English uses the subjunctive base form.'],
            ['C1', 'vocabulario', 'What does “substantial” mean in this context?', ['Very small', 'Considerable or important', 'Temporary', 'Unrelated'], 1, 'Substantial means considerable or significant.'],
            ['C1', 'comprension', '“The policy was implemented gradually.” What does gradually mean?', ['Suddenly', 'Little by little', 'Incorrectly', 'Without permission'], 1, 'Gradually means little by little.'],
            ['C1', 'gramatica', 'No sooner ___ the announcement than the audience reacted.', ['had he made', 'he made', 'has he made', 'he had made'], 0, 'No sooner at the beginning requires inversion with the past perfect.'],
            ['C1', 'vocabulario', 'What does “ambiguous” mean?', ['Having more than one possible meaning', 'Very obvious', 'Completely false', 'Easy to pronounce'], 0, 'Ambiguous means open to more than one interpretation.'],
            ['C1', 'comprension', '“The results were inconclusive.” What does this mean?', ['They proved everything', 'They did not provide a definite answer', 'They were published early', 'They were completely wrong'], 1, 'Inconclusive means not providing a definite conclusion.'],
            ['C1', 'gramatica', 'She denied ___ the confidential document.', ['to copy', 'copy', 'having copied', 'copied'], 2, 'Deny is followed by a gerund; having copied emphasizes the previous action.'],
            ['C2', 'gramatica', 'Were the negotiations to fail, the consequences ___ severe.', ['would be', 'will be', 'are', 'have been'], 0, 'Were ... to expresses a formal hypothetical condition.'],
            ['C2', 'vocabulario', 'What does “ubiquitous” mean?', ['Present or found everywhere', 'Extremely rare', 'Difficult to explain', 'Recently invented'], 0, 'Ubiquitous means present or found everywhere.'],
            ['C2', 'comprension', '“His argument was dismissed as specious.” What does specious mean?', ['Seemingly convincing but actually false', 'Supported by strong evidence', 'Very concise', 'Openly emotional'], 0, 'Specious describes an argument that appears correct but is not.'],
            ['C2', 'gramatica', 'Little ___ that the decision would cause controversy.', ['did they know', 'they knew', 'they did know', 'knew they'], 0, 'Little at the beginning requires subject-auxiliary inversion.'],
            ['C2', 'vocabulario', 'What does “pragmatic” mean?', ['Focused on practical results', 'Based only on theory', 'Impossible to apply', 'Highly emotional'], 0, 'Pragmatic means focused on practical results.'],
            ['C2', 'comprension', '“The proposal is tantamount to abandoning the project.” What does tantamount to mean?', ['Equivalent in effect to', 'Opposite to', 'Unrelated to', 'Easier than'], 0, 'Tantamount to means equivalent in effect to.'],
            ['C2', 'gramatica', 'Had it not been for the warning, the error ___ unnoticed.', ['might have gone', 'might go', 'will go', 'has gone'], 0, 'This is a third conditional referring to an unreal past situation.'],
            ['C2', 'vocabulario', 'What does “pervasive” mean?', ['Spreading widely throughout an area or group', 'Almost invisible', 'Strictly regulated', 'Short-lived'], 0, 'Pervasive means spreading widely throughout something.'],
            ['C2', 'comprension', '“The findings undermine the conventional explanation.” What does undermine mean?', ['Strengthen completely', 'Weaken or challenge', 'Repeat exactly', 'Translate'], 1, 'Undermine means weaken or challenge an idea.'],
            ['C2', 'gramatica', 'Were it not for the revised data, the conclusion ___ misleading.', ['would have been', 'will have been', 'has been', 'is being'], 0, 'Were it not for introduces a hypothetical condition about the past result.'],
            ];

        foreach ($advancedQuestions as [$level, $category, $question, $options, $correctAnswer, $explanation]) {
            $questions[] = [
                'language' => 'ingles',
                'level' => $level,
                'category' => $category,
                'question' => $question,
                'options' => json_encode($options),
                'correct_answer' => $correctAnswer,
                'explanation' => $explanation,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        $additionalLanguageQuestions = [
            'italiano' => [
                ['A1', 'vocabulario', '¿Qué significa “Buongiorno”?', ['Buenas noches', 'Buenos días', 'Hasta mañana', 'Gracias'], 1, 'Buongiorno se usa para saludar durante el día.'],
                ['A1', 'vocabulario', '¿Qué significa “Per favore”?', ['Por favor', 'De nada', 'Perdón', 'Adiós'], 0, 'Per favore significa por favor.'],
                ['A1', 'gramatica', 'Completa: “Io ___ Maria”.', ['sei', 'sono', 'è', 'siamo'], 1, 'Con io se usa sono.'],
                ['A1', 'vocabulario', '¿Qué significa “acqua”?', ['Pan', 'Agua', 'Leche', 'Café'], 1, 'Acqua significa agua.'],
                ['A1', 'gramatica', 'Completa: “Lui ___ italiano”.', ['sono', 'sei', 'è', 'siete'], 2, 'Con lui se usa è.'],
                ['A1', 'vocabulario', '¿Qué significa “casa”?', ['Calle', 'Casa', 'Escuela', 'Tienda'], 1, 'Casa significa casa.'],
                ['A1', 'comprension', '“Mi chiamo Luca”. ¿Qué significa?', ['Vivo en Luca', 'Me llamo Luca', 'Veo a Luca', 'Soy de Luca'], 1, 'Mi chiamo significa me llamo.'],
                ['A1', 'gramatica', 'Elige el artículo correcto: “___ libro”.', ['La', 'Lo', 'Il', 'Gli'], 2, 'Libro es masculino singular: il libro.'],
                ['A1', 'vocabulario', '¿Qué significa “grazie”?', ['Gracias', 'Hola', 'Por favor', 'Perdón'], 0, 'Grazie significa gracias.'],
                ['A1', 'gramatica', 'Completa: “Noi ___ studenti”.', ['siete', 'sono', 'siamo', 'è'], 2, 'Con noi se usa siamo.'],

                ['A2', 'gramatica', 'Completa: “Ieri noi ___ al cinema”.', ['andiamo', 'siamo andati', 'andremo', 'andate'], 1, 'El passato prossimo de andare usa essere: siamo andati.'],
                ['A2', 'vocabulario', '¿Qué significa “spesso”?', ['Raramente', 'A menudo', 'Nunca', 'Pronto'], 1, 'Spesso significa a menudo.'],
                ['A2', 'gramatica', 'Completa: “Maria ___ una lettera”.', ['scrivo', 'scrivi', 'scrive', 'scrivono'], 2, 'Con Maria, tercera persona singular, se usa scrive.'],
                ['A2', 'comprension', '“Devo prendere il treno alle otto”. ¿Qué debe hacer?', ['Tomar el tren a las ocho', 'Llegar a casa a las ocho', 'Comprar un coche', 'Esperar hasta mañana'], 0, 'Devo prendere il treno significa debo tomar el tren.'],
                ['A2', 'vocabulario', '¿Qué significa “vicino a”?', ['Lejos de', 'Al lado de', 'Antes de', 'Enfrente de'], 1, 'Vicino a significa cerca de o al lado de.'],
                ['A2', 'gramatica', 'Elige la forma correcta: “Le mele sono ___”.', ['rosso', 'rossa', 'rossi', 'rosse'], 3, 'Mele es femenino plural; el adjetivo concuerda: rosse.'],
                ['A2', 'gramatica', 'Completa: “A Luca ___ piace la musica”.', ['gli', 'lo', 'la', 'le'], 0, 'Con Luca, masculino singular, se usa gli piace.'],
                ['A2', 'comprension', '“Non posso uscire perché sto studiando”. ¿Por qué no puede salir?', ['Está trabajando', 'Está estudiando', 'Está durmiendo', 'Está viajando'], 1, 'Perché sto studiando significa porque estoy estudiando.'],
                ['A2', 'vocabulario', '¿Qué significa “biglietto”?', ['Maleta', 'Billete o entrada', 'Ventana', 'Horario'], 1, 'Biglietto puede significar billete o entrada.'],
                ['A2', 'gramatica', 'Completa: “Se piove, ___ a casa”.', ['resto', 'resti', 'restano', 'restare'], 0, 'Con io se conjuga resto.'],

                ['B1', 'gramatica', 'Completa: “Quando ero piccolo, ___ spesso dai nonni”.', ['vado', 'andavo', 'andrò', 'sono andato'], 1, 'El imperfetto describe hábitos en el pasado: andavo.'],
                ['B1', 'vocabulario', '¿Qué significa “rendersi conto”?', ['Darse cuenta', 'Darse prisa', 'Acostarse', 'Equivocarse'], 0, 'Rendersi conto significa darse cuenta.'],
                ['B1', 'gramatica', 'Completa: “Penso che lui ___ ragione”.', ['ha', 'abbia', 'avrà', 'avere'], 1, 'Después de penso che se usa el subjuntivo: abbia.'],
                ['B1', 'comprension', '“Benché fosse stanco, continuò a lavorare”. ¿Qué hizo?', ['Dejó de trabajar', 'Siguió trabajando aunque estaba cansado', 'Empezó a descansar', 'Trabajó desde casa'], 1, 'Benché introduce una concesión: aunque estuviera cansado.'],
                ['B1', 'vocabulario', '¿Qué significa “affidabile”?', ['Confiable', 'Ruidoso', 'Avergonzado', 'Afilado'], 0, 'Affidabile significa confiable.'],
                ['B1', 'gramatica', 'Completa: “Se avessi più tempo, ___ un corso”.', ['frequento', 'frequenterei', 'frequentavo', 'frequenterò'], 1, 'El periodo hipotético usa congiuntivo imperfecto y condizionale: frequenterei.'],
                ['B1', 'comprension', '“Il colloquio è stato rimandato a lunedì”. ¿Qué ocurrió?', ['Se canceló definitivamente', 'Se aplazó hasta el lunes', 'Comenzó el lunes', 'Se realizó el viernes'], 1, 'Rimandato significa aplazado.'],
                ['B1', 'gramatica', 'Elige la forma correcta: “La ragazza ___ ho parlato è mia cugina”.', ['che', 'con cui', 'chi', 'dove'], 1, 'Parlare con una persona requiere con cui.'],
                ['B1', 'vocabulario', '¿Qué significa “nonostante”?', ['A causa de', 'A pesar de', 'Antes de', 'En lugar de'], 1, 'Nonostante expresa concesión: a pesar de.'],
                ['B1', 'gramatica', 'Completa: “Appena ___, ti chiamerò”.', ['arrivo', 'arriverò', 'arrivavo', 'sono arrivato'], 0, 'Después de appena con sentido futuro se usa presente: appena arrivo.'],

                ['B2', 'gramatica', 'Completa: “Se me lo ___ prima, avrei potuto aiutarti”.', ['dicevi', 'avessi detto', 'dirai', 'dici'], 1, 'El periodo hipotético irreal del pasado usa congiuntivo trapassato: avessi detto.'],
                ['B2', 'vocabulario', '¿Qué significa “svolgere un compito”?', ['Evitar una tarea', 'Realizar una tarea', 'Corregir un examen', 'Posponer un trabajo'], 1, 'Svolgere un compito significa realizar o llevar a cabo una tarea.'],
                ['B2', 'gramatica', 'Elige la forma correcta: “Benché ___ molte difficoltà, il progetto riuscì”.', ['c’erano', 'ci fossero', 'ci saranno', 'esserci'], 1, 'Benché requiere subjuntivo; aquí ci fossero.'],
                ['B2', 'comprension', '“La misura è stata accolta con riserve”. ¿Cómo fue recibida?', ['Con entusiasmo unánime', 'Con ciertas dudas o cautelas', 'Fue ignorada', 'Fue rechazada legalmente'], 1, 'Con riserve significa con reservas o cautela.'],
                ['B2', 'vocabulario', '¿Qué significa “esaustivo”?', ['Breve e incompleto', 'Completo y detallado', 'Confuso', 'Obsoleto'], 1, 'Esaustivo significa completo y minucioso.'],
                ['B2', 'gramatica', 'Completa: “Avrei preferito che tu ___ con noi”.', ['vieni', 'venissi', 'verrai', 'venire'], 1, 'Preferirei che rige congiuntivo imperfetto en esta construcción.'],
                ['B2', 'comprension', '“La sua spiegazione lascia intendere un possibile cambiamento”. ¿Qué implica?', ['El cambio ya ocurrió', 'Sugiere que podría haber un cambio', 'Descarta todo cambio', 'No ofrece ninguna pista'], 1, 'Lascia intendere significa deja entender o sugiere.'],
                ['B2', 'gramatica', 'Elige el pronombre correcto: “Il progetto ___ ti parlavo è stato approvato”.', ['di cui', 'che', 'chi', 'il quale'], 0, 'La expresión parlare di requiere di cui.'],
                ['B2', 'vocabulario', '¿Qué significa “tuttavia”?', ['Por consiguiente', 'Sin embargo', 'Por ejemplo', 'Mientras tanto'], 1, 'Tuttavia expresa contraste: sin embargo.'],
                ['B2', 'gramatica', 'Completa: “Pur ___ in disaccordo, hanno collaborato”.', ['essendo', 'sono', 'erano', 'stati'], 0, 'Pur essendo significa aun estando; pur va seguido de gerundio.'],

                ['C1', 'gramatica', 'Completa: “Qualora ___ ulteriori informazioni, La contatteremo”.', ['servono', 'servissero', 'serviranno', 'servire'], 1, 'Qualora puede regir congiuntivo imperfetto en una hipótesis formal.'],
                ['C1', 'vocabulario', '¿Qué significa “inequivocabile”?', ['Ambiguo', 'Que no deja lugar a dudas', 'Difícil de pronunciar', 'Poco frecuente'], 1, 'Inequivocabile significa inequívoco, sin dudas.'],
                ['C1', 'comprension', '“La decisione è stata presa a discapito delle alternative”. ¿Qué indica?', ['Se favorecieron todas las alternativas', 'Se tomó la decisión perjudicando otras opciones', 'No se tomó ninguna decisión', 'Se aplazaron las alternativas'], 1, 'A discapito di significa en detrimento o perjuicio de.'],
                ['C1', 'gramatica', 'Completa: “Non che la proposta ___ priva di meriti, ma va rivista”.', ['è', 'sia', 'sarà', 'essere'], 1, 'Non che introduce una valoración con subjuntivo: sia.'],
                ['C1', 'vocabulario', '¿Qué significa “circostanziato”?', ['Vago', 'Detallado y respaldado por circunstancias', 'Contradictorio', 'Imprevisto'], 1, 'Circostanziato significa detallado y fundamentado.'],
                ['C1', 'gramatica', 'Elige la forma correcta: “È una questione ___ occorre occuparsi subito”.', ['che', 'di cui', 'della quale', 'cui'], 1, 'Occuparsi di requiere di cui.'],
                ['C1', 'comprension', '“L’ipotesi non è suffragata dai dati disponibili”. ¿Qué significa?', ['Los datos confirman la hipótesis', 'Los datos disponibles no la respaldan', 'La hipótesis fue descartada por completo', 'Los datos no están disponibles'], 1, 'Suffragata significa respaldada o apoyada por pruebas.'],
                ['C1', 'vocabulario', '¿Qué significa “pregiudicare”?', ['Mejorar notablemente', 'Perjudicar o comprometer', 'Examinar con detalle', 'Hacer público'], 1, 'Pregiudicare significa perjudicar o poner en riesgo.'],
                ['C1', 'gramatica', 'Completa: “Ben pochi ___ conto delle conseguenze di quella scelta”.', ['si erano resi', 'si era reso', 'si renderà', 'rendersi'], 0, 'Con ben pochi se usa el plural: si erano resi conto.'],
                ['C1', 'comprension', '“L’intervento ha sortito effetti trascurabili”. ¿Qué efecto tuvo?', ['Un efecto muy importante', 'Efectos insignificantes', 'Ningún efecto previsto', 'Un efecto duradero'], 1, 'Trascurabili significa insignificantes o desdeñables.'],

                ['C2', 'vocabulario', '¿Qué significa “ apodittico”?', ['Provisional', 'Afirmado como indiscutible', 'Basado en estadísticas', 'Difícil de comprender'], 1, 'Apodittico describe algo presentado como evidente o indiscutible.'],
                ['C2', 'gramatica', 'Completa: “Se mai ___ a verificarsi una simile eventualità, agiremo di conseguenza”.', ['dovesse', 'dovrà', 'deve', 'dovrebbe'], 0, 'Se mai dovesse expresa una hipótesis remota con congiuntivo imperfetto.'],
                ['C2', 'comprension', '“L’argomentazione, per quanto suggestiva, è fallace”. ¿Qué quiere decir?', ['Es convincente y correcta', 'Aunque atractiva, contiene un razonamiento erróneo', 'Es demasiado breve', 'No intenta convencer'], 1, 'Fallace significa engañosa o basada en un error.'],
                ['C2', 'vocabulario', '¿Qué significa “dirimente”?', ['Que resuelve definitivamente una cuestión', 'Que plantea una duda menor', 'Que resulta irrelevante', 'Que se puede aplazar'], 0, 'Dirimente es aquello que resuelve una disputa o cuestión.'],
                ['C2', 'gramatica', 'Elige la forma correcta: “Comunque la si ___, la questione resta aperta”.', ['metta', 'mette', 'metterà', 'metteva'], 0, 'La fórmula comunque la si metta usa subjuntivo con valor concesivo.'],
                ['C2', 'comprension', '“La clausola è suscettibile di interpretazioni divergenti”. ¿Qué implica?', ['Solo admite una interpretación', 'Puede interpretarse de maneras diferentes', 'No tiene efecto legal', 'Fue eliminada del documento'], 1, 'Suscettibile di indica que algo puede admitir o estar sujeto a algo.'],
                ['C2', 'vocabulario', '¿Qué significa “inficiare”?', ['Confirmar sin reservas', 'Invalidar o debilitar la validez', 'Resumir con claridad', 'Repetir literalmente'], 1, 'Inficiare significa comprometer o invalidar la validez.'],
                ['C2', 'gramatica', 'Completa: “Non fosse stato per il suo intuito, l’equivoco ___”.', ['sarebbe perdurato', 'perdura', 'perdurerebbe', 'è perdurato'], 0, 'La condición irreal del pasado se expresa con congiuntivo trapassato y condizionale passato.'],
                ['C2', 'comprension', '“Il provvedimento ha una portata tutt’altro che marginale”. ¿Qué se afirma?', ['Su importancia es mínima', 'Su alcance es considerable', 'Su aplicación es imposible', 'Su efecto es temporal'], 1, 'Tutt’altro che marginale significa muy lejos de ser insignificante.'],
                ['C2', 'vocabulario', '¿Qué significa “dirimente” en un debate?', ['Decisivo para resolverlo', 'Accesorio y prescindible', 'Contrario a los hechos', 'Difícil de resumir'], 0, 'En un debate, dirimente es un elemento decisivo para resolver la cuestión.'],
            ],
            'portugues' => [
                ['A1', 'vocabulario', '¿Qué significa “Bom dia”?', ['Buenas noches', 'Buenos días', 'Hasta luego', 'Por favor'], 1, 'Bom dia significa buenos días.'],
                ['A1', 'vocabulario', '¿Qué significa “obrigado”?', ['Gracias', 'Hola', 'Perdón', 'Adiós'], 0, 'Obrigado es gracias dicho por un hombre; obrigada, por una mujer.'],
                ['A1', 'gramatica', 'Completa: “Eu ___ estudante”.', ['é', 'sou', 'são', 'somos'], 1, 'Con eu se usa sou.'],
                ['A1', 'vocabulario', '¿Qué significa “água”?', ['Agua', 'Leche', 'Pan', 'Café'], 0, 'Água significa agua.'],
                ['A1', 'gramatica', 'Completa: “Ela ___ brasileira”.', ['sou', 'é', 'são', 'somos'], 1, 'Con ela se usa é.'],
                ['A1', 'vocabulario', '¿Qué significa “casa”?', ['Escuela', 'Casa', 'Calle', 'Mesa'], 1, 'Casa significa casa.'],
                ['A1', 'comprension', '“Meu nome é João”. ¿Qué significa?', ['Vivo con João', 'Mi nombre es João', 'Veo a João', 'Soy de João'], 1, 'Meu nome é significa mi nombre es.'],
                ['A1', 'gramatica', 'Elige el artículo correcto: “___ livro”.', ['A', 'O', 'As', 'Uma'], 1, 'Livro es masculino singular: o livro.'],
                ['A1', 'vocabulario', '¿Qué significa “por favor”?', ['Por favor', 'Gracias', 'De nada', 'Perdón'], 0, 'Por favor tiene el mismo significado en portugués.'],
                ['A1', 'gramatica', 'Completa: “Nós ___ amigos”.', ['é', 'sou', 'somos', 'são'], 2, 'Con nós se usa somos.'],

                ['A2', 'gramatica', 'Completa: “Ontem eu ___ ao mercado”.', ['vou', 'fui', 'irei', 'ia'], 1, 'Fui es el pretérito de ir para eu.'],
                ['A2', 'vocabulario', '¿Qué significa “talvez”?', ['Siempre', 'Tal vez', 'Ayer', 'Pronto'], 1, 'Talvez significa tal vez o quizá.'],
                ['A2', 'gramatica', 'Completa: “Ela ___ trabalhando agora”.', ['está', 'são', 'tem', 'foi'], 0, 'Estar + gerundio expresa una acción en curso: está trabalhando.'],
                ['A2', 'comprension', '“Preciso pegar o ônibus às sete”. ¿Qué debe hacer?', ['Tomar el autobús a las siete', 'Llegar a casa a las siete', 'Comprar un coche', 'Esperar hasta mañana'], 0, 'Preciso pegar o ônibus significa necesito tomar el autobús.'],
                ['A2', 'vocabulario', '¿Qué significa “perto de”?', ['Lejos de', 'Cerca de', 'Antes de', 'Debajo de'], 1, 'Perto de significa cerca de.'],
                ['A2', 'gramatica', 'Elige la forma correcta: “As casas são ___”.', ['branco', 'branca', 'brancos', 'brancas'], 3, 'Casas es femenino plural, por eso brancas.'],
                ['A2', 'gramatica', 'Completa: “Eu ___ um café, por favor”.', ['queria', 'quero', 'querem', 'querer'], 1, 'Con eu en presente se usa quero.'],
                ['A2', 'comprension', '“Não saí porque estava chovendo”. ¿Por qué no salió?', ['Porque estaba lloviendo', 'Porque estaba trabajando', 'Porque perdió el autobús', 'Porque estaba enfermo'], 0, 'Estava chovendo significa estaba lloviendo.'],
                ['A2', 'vocabulario', '¿Qué significa “passagem”?', ['Pasaje o billete', 'Maleta', 'Ventana', 'Desayuno'], 0, 'Passagem puede referirse a un billete o pasaje.'],
                ['A2', 'gramatica', 'Completa: “Se fizer sol, nós ___ à praia”.', ['vamos', 'íamos', 'fomos', 'ir'], 0, 'En una condición posible, la consecuencia puede ir en presente: vamos.'],

                ['B1', 'gramatica', 'Completa: “Quando eu era criança, ___ no campo”.', ['brinco', 'brincava', 'brincarei', 'brinquei'], 1, 'El imperfecto expresa hábito pasado: brincava.'],
                ['B1', 'vocabulario', '¿Qué significa “perceber”?', ['Darse cuenta o percibir', 'Aplazar', 'Prestar', 'Esconder'], 0, 'Perceber significa percibir o darse cuenta.'],
                ['B1', 'gramatica', 'Completa: “Espero que ele ___ a tempo”.', ['chega', 'chegue', 'chegou', 'chegar'], 1, 'Después de espero que se usa subjuntivo: chegue.'],
                ['B1', 'comprension', '“Embora estivesse cansada, continuou trabalhando”. ¿Qué hizo?', ['Dejó de trabajar', 'Siguió trabajando aunque estaba cansada', 'Se fue a dormir', 'Empezó más tarde'], 1, 'Embora introduce una concesión: aunque.'],
                ['B1', 'vocabulario', '¿Qué significa “confiável”?', ['Confiable', 'Ruidoso', 'Avergonzado', 'Afilado'], 0, 'Confiável significa confiable.'],
                ['B1', 'gramatica', 'Completa: “Se eu tivesse dinheiro, ___ uma viagem”.', ['faço', 'faria', 'fiz', 'farei'], 1, 'La hipótesis usa imperfecto de subjuntivo y condicional: faria.'],
                ['B1', 'comprension', '“A reunião foi adiada para sexta-feira”. ¿Qué ocurrió?', ['Se canceló para siempre', 'Se aplazó hasta el viernes', 'Comenzó el viernes', 'Se realizó el jueves'], 1, 'Adiada significa aplazada.'],
                ['B1', 'gramatica', 'Completa: “Este é o livro ___ falei ontem”.', ['que', 'de que', 'quem', 'onde'], 1, 'Falar de algo requiere de que en esta oración.'],
                ['B1', 'vocabulario', '¿Qué significa “apesar de”?', ['A causa de', 'A pesar de', 'Antes de', 'En lugar de'], 1, 'Apesar de expresa concesión.'],
                ['B1', 'gramatica', 'Completa: “Assim que eu ___, aviso você”.', ['chego', 'chegarei', 'chegava', 'chegar'], 3, 'En una referencia futura, assim que rige futuro de subjuntivo: chegar.'],

                ['B2', 'gramatica', 'Completa: “Se eu ___ disso, teria agido de outra forma”.', ['sabia', 'soubesse', 'sei', 'saberei'], 1, 'La hipótesis irreal usa imperfecto de subjuntivo: soubesse.'],
                ['B2', 'vocabulario', '¿Qué significa “desempenhar uma função”?', ['Evitar una tarea', 'Desempeñar una función', 'Solicitar un empleo', 'Cambiar de opinión'], 1, 'Desempenhar uma função significa cumplir o desempeñar una función.'],
                ['B2', 'gramatica', 'Completa: “Embora ___ vários obstáculos, o projeto avançou”.', ['havia', 'houvesse', 'haverá', 'haver'], 1, 'Embora rige subjuntivo en este contexto: houvesse.'],
                ['B2', 'comprension', '“A proposta foi recebida com ressalvas”. ¿Cómo fue recibida?', ['Con aprobación total', 'Con reservas o cautela', 'Fue ignorada', 'Fue retirada'], 1, 'Ressalvas son reservas o condiciones.'],
                ['B2', 'vocabulario', '¿Qué significa “abrangente”?', ['Limitado', 'Amplio y completo', 'Confuso', 'Temporal'], 1, 'Abrangente significa amplio o exhaustivo.'],
                ['B2', 'gramatica', 'Completa: “Preferia que vocês ___ mais cedo”.', ['chegam', 'chegassem', 'chegarão', 'chegar'], 1, 'Preferia que rige imperfecto de subjuntivo: chegassem.'],
                ['B2', 'comprension', '“A declaração sugere uma mudança iminente”. ¿Qué indica?', ['El cambio ya terminó', 'El cambio parece próximo', 'No habrá cambios', 'El cambio fue descartado'], 1, 'Iminente significa que está a punto de ocurrir.'],
                ['B2', 'gramatica', 'Completa: “O assunto ___ lhe falei é confidencial”.', ['que', 'de que', 'quem', 'onde'], 1, 'Falar de algo requiere de que.'],
                ['B2', 'vocabulario', '¿Qué significa “todavia”?', ['Por consiguiente', 'Sin embargo', 'Por ejemplo', 'Mientras tanto'], 1, 'Todavia significa sin embargo o no obstante.'],
                ['B2', 'gramatica', 'Completa: “Mesmo ___ em desacordo, colaboraram”.', ['estando', 'estão', 'estavam', 'estado'], 0, 'Mesmo estando significa aun estando; se usa gerundio.'],

                ['C1', 'gramatica', 'Completa: “Caso ___ novas evidências, o processo será reaberto”.', ['surjam', 'surgem', 'surgirão', 'surgir'], 0, 'Caso rige subjuntivo: surjam.'],
                ['C1', 'vocabulario', '¿Qué significa “inequívoco”?', ['Ambiguo', 'Que no deja lugar a dudas', 'Poco frecuente', 'Imposible de probar'], 1, 'Inequívoco significa claro y sin ambigüedad.'],
                ['C1', 'comprension', '“A medida foi adotada em detrimento de outras prioridades”. ¿Qué implica?', ['Benefició todas las prioridades', 'Se adoptó perjudicando otras prioridades', 'No se adoptó ninguna medida', 'Las prioridades fueron aplazadas'], 1, 'Em detrimento de significa en perjuicio de.'],
                ['C1', 'gramatica', 'Completa: “Não que a decisão ___ desprovida de mérito, mas é questionável”.', ['é', 'seja', 'será', 'ser'], 1, 'Não que introduce una valoración con subjuntivo: seja.'],
                ['C1', 'vocabulario', '¿Qué significa “contundente” en “provas contundentes”?', ['Débiles', 'Convincentes y decisivas', 'Incompletas', 'Recientes'], 1, 'Contundente describe pruebas fuertes y convincentes.'],
                ['C1', 'gramatica', 'Completa: “É uma questão ___ precisamos nos debruçar”.', ['que', 'sobre a qual', 'quem', 'onde'], 1, 'Debruçar-se sobre algo requiere sobre a qual.'],
                ['C1', 'comprension', '“A hipótese não encontra respaldo nos dados”. ¿Qué significa?', ['Los datos la confirman', 'Los datos no la respaldan', 'La hipótesis fue probada', 'Los datos no existen'], 1, 'Encontrar respaldo significa contar con apoyo o evidencia.'],
                ['C1', 'vocabulario', '¿Qué significa “comprometer a validade”?', ['Confirmar la validez', 'Poner en riesgo la validez', 'Explicar la validez', 'Medir la validez'], 1, 'Comprometer puede significar poner en riesgo.'],
                ['C1', 'gramatica', 'Completa: “Mal ___ a reunião, percebeu o equívoco”.', ['começou', 'tinha começado', 'começaria', 'começar'], 1, 'El pluscuamperfecto indica que ya había comenzado cuando lo percibió.'],
                ['C1', 'comprension', '“Os efeitos foram pouco expressivos”. ¿Cómo fueron?', ['Muy notables', 'De poca importancia', 'Permanentes', 'Imprevisibles'], 1, 'Pouco expressivos significa poco significativos.'],

                ['C2', 'vocabulario', '¿Qué significa “peremptório”?', ['Provisional', 'Categórico y concluyente', 'Vacilante', 'Accidental'], 1, 'Peremptório significa categórico o definitivo.'],
                ['C2', 'gramatica', 'Completa: “Se porventura ___ a ocorrer tal cenário, haverá revisão”.', ['viesse', 'virá', 'vem', 'viria'], 0, 'Se porventura viesse expresa una hipótesis remota con imperfecto de subjuntivo.'],
                ['C2', 'comprension', '“O argumento, embora sedutor, é falacioso”. ¿Qué significa?', ['Es atractivo pero engañoso', 'Es correcto y concluyente', 'Es breve y objetivo', 'No pretende convencer'], 0, 'Falacioso significa engañoso o basado en razonamiento falso.'],
                ['C2', 'vocabulario', '¿Qué significa “dirimir uma controvérsia”?', ['Ampliar una controversia', 'Resolver una controversia', 'Ocultar una controversia', 'Aplazar una controversia'], 1, 'Dirimir significa resolver una disputa.'],
                ['C2', 'gramatica', 'Completa: “Seja como ___, a questão permanece sem solução”.', ['for', 'é', 'será', 'fosse'], 0, 'La expresión fija seja como for significa sea como sea.'],
                ['C2', 'comprension', '“A cláusula é passível de interpretações díspares”. ¿Qué indica?', ['Solo permite una interpretación', 'Puede admitir interpretaciones muy distintas', 'No tiene validez', 'Fue suprimida'], 1, 'Díspares significa diferentes o divergentes.'],
                ['C2', 'vocabulario', '¿Qué significa “infirmar uma conclusão”?', ['Confirmarla plenamente', 'Debilitar o refutar su fundamento', 'Resumirla', 'Publicarla'], 1, 'Infirmar significa debilitar o refutar una afirmación.'],
                ['C2', 'gramatica', 'Completa: “Não fosse a intervenção, o impasse ___”.', ['teria persistido', 'persiste', 'persistiria agora', 'persistiu'], 0, 'La condición irreal pasada usa imperfecto de subjuntivo y condicional compuesto.'],
                ['C2', 'comprension', '“A iniciativa está longe de ser despicienda”. ¿Qué se afirma?', ['Es insignificante', 'Tiene importancia y no debe despreciarse', 'Es imposible', 'Fue abandonada'], 1, 'Longe de ser despicienda significa que está lejos de ser insignificante.'],
                ['C2', 'vocabulario', '¿Qué significa “incontornável” en una discusión?', ['Fácil de evitar', 'Que no se puede eludir', 'Poco relevante', 'Difícil de traducir'], 1, 'Incontornável significa inevitable o imposible de evitar.'],
            ],
            'polaco' => [
                ['A1', 'vocabulario', '¿Qué significa “Dzień dobry”?', ['Buenas noches', 'Buenos días', 'Gracias', 'Adiós'], 1, 'Dzień dobry es un saludo formal diurno.'],
                ['A1', 'vocabulario', '¿Qué significa “Dziękuję”?', ['Por favor', 'Gracias', 'Hola', 'Perdón'], 1, 'Dziękuję significa gracias.'],
                ['A1', 'gramatica', 'Completa: “Ja ___ studentem”.', ['jestem', 'jesteś', 'jest', 'są'], 0, 'Con ja se usa jestem.'],
                ['A1', 'vocabulario', '¿Qué significa “woda”?', ['Agua', 'Leche', 'Pan', 'Café'], 0, 'Woda significa agua.'],
                ['A1', 'gramatica', 'Completa: “Ona ___ z Polski”.', ['jestem', 'jesteś', 'jest', 'jesteśmy'], 2, 'Con ona se usa jest.'],
                ['A1', 'vocabulario', '¿Qué significa “dom”?', ['Escuela', 'Casa', 'Calle', 'Tienda'], 1, 'Dom significa casa.'],
                ['A1', 'comprension', '“Mam na imię Anna”. ¿Qué significa?', ['Vivo con Anna', 'Me llamo Anna', 'Veo a Anna', 'Soy de Anna'], 1, 'Mam na imię significa me llamo.'],
                ['A1', 'gramatica', 'Elige la forma correcta: “To ___ książka”.', ['jest', 'są', 'jestem', 'jesteście'], 0, 'To jest książka significa esto es un libro.'],
                ['A1', 'vocabulario', '¿Qué significa “proszę”?', ['Por favor / aquí tiene', 'Gracias', 'Hasta luego', 'Buenos días'], 0, 'Proszę se usa para decir por favor o aquí tiene.'],
                ['A1', 'gramatica', 'Completa: “My ___ kawę”.', ['lubię', 'lubisz', 'lubi', 'lubią'], 0, 'Con my se usa lubię.'],

                ['A2', 'gramatica', 'Completa: “Wczoraj ___ do kina”.', ['idę', 'poszedłem', 'pójdę', 'chodzić'], 1, 'Poszedłem es una forma masculina de pasado de ir.'],
                ['A2', 'vocabulario', '¿Qué significa “często”?', ['Nunca', 'A menudo', 'Raramente', 'Pronto'], 1, 'Często significa a menudo.'],
                ['A2', 'gramatica', 'Completa: “Ona ___ książkę”.', ['czytam', 'czytasz', 'czyta', 'czytają'], 2, 'Con ona se usa czyta.'],
                ['A2', 'comprension', '“Muszę złapać autobus o ósmej”. ¿Qué necesita hacer?', ['Tomar el autobús a las ocho', 'Llegar a casa a las ocho', 'Comprar un billete de tren', 'Esperar hasta mañana'], 0, 'Muszę złapać autobus significa necesito tomar el autobús.'],
                ['A2', 'vocabulario', '¿Qué significa “blisko”?', ['Lejos', 'Cerca', 'Arriba', 'Detrás'], 1, 'Blisko significa cerca.'],
                ['A2', 'gramatica', 'Elige la forma correcta: “Mam ___ jabłka”.', ['czerwony', 'czerwona', 'czerwone', 'czerwoni'], 2, 'Jabłka es neutro plural y concuerda con czerwone.'],
                ['A2', 'gramatica', 'Completa: “Podoba ___ ta muzyka”.', ['mi', 'mnie', 'ja', 'my'], 0, 'La construcción podoba mi się expresa que algo me gusta.'],
                ['A2', 'comprension', '“Nie wychodzę, ponieważ pada deszcz”. ¿Por qué no sale?', ['Porque está lloviendo', 'Porque está trabajando', 'Porque perdió el autobús', 'Porque está cansado'], 0, 'Pada deszcz significa está lloviendo.'],
                ['A2', 'vocabulario', '¿Qué significa “bilet”?', ['Billete o entrada', 'Maleta', 'Ventana', 'Desayuno'], 0, 'Bilet significa billete o entrada.'],
                ['A2', 'gramatica', 'Completa: “Jeśli będzie ciepło, ___ do parku”.', ['pójdziemy', 'szliśmy', 'chodziliśmy', 'iść'], 0, 'Pójdziemy expresa iremos en esta condición futura.'],

                ['B1', 'gramatica', 'Completa: “Kiedy byłem dzieckiem, często ___ u babci”.', ['mieszkam', 'mieszkałem', 'zamieszkam', 'zamieszkałem'], 1, 'El imperfectivo pasado describe una situación habitual: mieszkałem.'],
                ['B1', 'vocabulario', '¿Qué significa “zauważyć”?', ['Darse cuenta o notar', 'Aplazar', 'Prestar', 'Esconder'], 0, 'Zauważyć significa notar o advertir.'],
                ['B1', 'gramatica', 'Completa: “Mam nadzieję, że on ___ na czas”.', ['przyjdzie', 'przyszedłby', 'przychodził', 'przyjść'], 0, 'Przyjdzie es la forma futura perfectiva de llegar.'],
                ['B1', 'comprension', '“Chociaż był zmęczony, kontynuował pracę”. ¿Qué hizo?', ['Dejó de trabajar', 'Siguió trabajando aunque estaba cansado', 'Se fue a dormir', 'Empezó a descansar'], 1, 'Chociaż significa aunque.'],
                ['B1', 'vocabulario', '¿Qué significa “godny zaufania”?', ['Confiable', 'Ruidoso', 'Avergonzado', 'Afilado'], 0, 'Godny zaufania significa digno de confianza.'],
                ['B1', 'gramatica', 'Completa: “Gdybym miał więcej czasu, ___ drugi język”.', ['uczę się', 'uczyłbym się', 'nauczyłem się', 'nauczę się'], 1, 'La hipótesis usa gdybym y condicional: uczyłbym się.'],
                ['B1', 'comprension', '“Spotkanie zostało przełożone na piątek”. ¿Qué ocurrió?', ['Se canceló para siempre', 'Se aplazó al viernes', 'Empezó el viernes', 'Se realizó el jueves'], 1, 'Przełożone significa aplazado o reprogramado.'],
                ['B1', 'gramatica', 'Completa: “To jest osoba, ___ wczoraj rozmawiałem”.', ['którą', 'z którą', 'której', 'która'], 1, 'Rozmawiać z kimś requiere z którą.'],
                ['B1', 'vocabulario', '¿Qué significa “mimo że”?', ['Debido a que', 'Aunque', 'Antes de que', 'En vez de'], 1, 'Mimo że significa aunque.'],
                ['B1', 'gramatica', 'Completa: “Kiedy ___, zadzwoń do mnie”.', ['wrócisz', 'wracałeś', 'wróciłbyś', 'wracać'], 0, 'En una referencia futura tras kiedy se usa presente perfectivo: wrócisz.'],

                ['B2', 'gramatica', 'Completa: “Gdybym ___ o tym wcześniej, postąpiłbym inaczej”.', ['wiedział', 'wiem', 'będę wiedział', 'wiedzieć'], 0, 'El condicional pasado usa gdybym + participio: wiedział.'],
                ['B2', 'vocabulario', '¿Qué significa “pełnić funkcję”?', ['Evitar una tarea', 'Desempeñar una función', 'Solicitar empleo', 'Cambiar de opinión'], 1, 'Pełnić funkcję significa desempeñar una función.'],
                ['B2', 'gramatica', 'Completa: “Mimo że ___ wiele przeszkód, projekt zakończono”.', ['było', 'były', 'będzie', 'być'], 0, 'La construcción impersonal było wiele usa neutro singular.'],
                ['B2', 'comprension', '“Propozycja spotkała się z zastrzeżeniami”. ¿Cómo fue recibida?', ['Con aprobación total', 'Con reservas', 'Fue ignorada', 'Fue retirada'], 1, 'Zastrzeżenia son objeciones o reservas.'],
                ['B2', 'vocabulario', '¿Qué significa “wyczerpujący”?', ['Breve e incompleto', 'Completo y detallado', 'Confuso', 'Temporal'], 1, 'Wyczerpujący significa exhaustivo.'],
                ['B2', 'gramatica', 'Completa: “Wolałbym, żebyście ___ wcześniej”.', ['przychodzicie', 'przyszli', 'przyjdziecie', 'przyjść'], 1, 'Después de wolałbym, żeby se usa pasado en la subordinada desiderativa.'],
                ['B2', 'comprension', '“Oświadczenie zapowiada rychłą zmianę”. ¿Qué anuncia?', ['Un cambio ya terminado', 'Un cambio próximo', 'Que no habrá cambios', 'Que se descartó el cambio'], 1, 'Rychłą significa próxima o inminente.'],
                ['B2', 'gramatica', 'Completa: “To temat, ___ rozmawialiśmy wczoraj”.', ['który', 'o którym', 'kogo', 'gdzie'], 1, 'Rozmawiać o czymś requiere o którym.'],
                ['B2', 'vocabulario', '¿Qué significa “niemniej jednak”?', ['Por consiguiente', 'Sin embargo', 'Por ejemplo', 'Mientras tanto'], 1, 'Niemniej jednak significa no obstante.'],
                ['B2', 'gramatica', 'Completa: “Nawet ___ nie zgadzając, współpracowali”.', ['będąc', 'są', 'byli', 'być'], 0, 'Nawet będąc significa aun estando; se usa gerundio.'],

                ['C1', 'gramatica', 'Completa: “Gdyby ___ nowe dowody, sprawa zostałaby wznowiona”.', ['pojawiły się', 'pojawiają się', 'pojawią się', 'pojawiać się'], 0, 'La hipótesis irreal usa gdyby y pasado: pojawiły się.'],
                ['C1', 'vocabulario', '¿Qué significa “jednoznaczny”?', ['Ambiguo', 'Que no deja lugar a dudas', 'Poco frecuente', 'Difícil de probar'], 1, 'Jednoznaczny significa inequívoco.'],
                ['C1', 'comprension', '“Decyzję podjęto kosztem innych priorytetów”. ¿Qué implica?', ['Se favorecieron todas las prioridades', 'La decisión perjudicó otras prioridades', 'No se tomó decisión', 'Las prioridades se aplazaron'], 1, 'Kosztem significa a costa de.'],
                ['C1', 'gramatica', 'Completa: “Nie żeby propozycja ___ pozbawiona zalet, ale wymaga zmian”.', ['jest', 'była', 'będzie', 'być'], 1, 'Nie żeby introduce una valoración hipotética; aquí by była expresa esa reserva.'],
                ['C1', 'vocabulario', '¿Qué significa “niepodważalny”?', ['Fácil de refutar', 'Irrefutable', 'Temporal', 'Incompleto'], 1, 'Niepodważalny significa irrefutable o incontestable.'],
                ['C1', 'gramatica', 'Completa: “To kwestia, ___ należy się niezwłocznie zająć”.', ['którą', 'którą się', 'którą należy', 'którą należy się'], 3, 'Zająć się czymś exige instrumental; la construcción es kwestią, którą należy się zająć.'],
                ['C1', 'comprension', '“Hipoteza nie znajduje potwierdzenia w dostępnych danych”. ¿Qué significa?', ['Los datos la confirman', 'Los datos disponibles no la confirman', 'La hipótesis fue probada', 'Los datos no existen'], 1, 'Nie znajduje potwierdzenia significa que no encuentra confirmación.'],
                ['C1', 'vocabulario', '¿Qué significa “podważać wiarygodność”?', ['Confirmar la credibilidad', 'Socavar la credibilidad', 'Explicar la credibilidad', 'Medir la credibilidad'], 1, 'Podważać wiarygodność significa poner en duda o socavar la credibilidad.'],
                ['C1', 'gramatica', 'Completa: “Zanim ___ posiedzenie, zauważono błąd”.', ['rozpoczęło się', 'rozpocznie się', 'rozpoczyna się', 'rozpocząć się'], 0, 'El pasado perfectivo rozpoczęło się marca que la sesión ya empezó antes de advertir el error.'],
                ['C1', 'comprension', '“Skutki okazały się znikome”. ¿Cómo fueron los efectos?', ['Muy importantes', 'Insignificantes', 'Permanentes', 'Imprevisibles'], 1, 'Znikome significa insignificantes.'],

                ['C2', 'vocabulario', '¿Qué significa “kategoryczny”?', ['Provisional', 'Categórico y concluyente', 'Vacilante', 'Accidental'], 1, 'Kategoryczny significa categórico o tajante.'],
                ['C2', 'gramatica', 'Completa: “Gdyby kiedykolwiek ___ do takiej sytuacji, zareagujemy”.', ['doszło', 'dojdzie', 'dochodzi', 'doszłoby'], 0, 'Gdyby doszło expresa una hipótesis remota con pasado perfectivo.'],
                ['C2', 'comprension', '“Argument, choć sugestywny, jest sofistyczny”. ¿Qué se afirma?', ['Es atractivo pero engañoso', 'Es correcto y concluyente', 'Es breve y objetivo', 'No pretende convencer'], 0, 'Sofistyczny describe un razonamiento aparentemente convincente pero falaz.'],
                ['C2', 'vocabulario', '¿Qué significa “rozstrzygnąć spór”?', ['Ampliar una disputa', 'Resolver una disputa', 'Ocultar una disputa', 'Aplazar una disputa'], 1, 'Rozstrzygnąć spór significa resolver o decidir una disputa.'],
                ['C2', 'gramatica', 'Completa: “Jakkolwiek ___, problem pozostaje nierozwiązany”.', ['na to spojrzeć', 'patrzy', 'spojrzy', 'patrzył'], 0, 'Jakkolwiek na to spojrzeć significa se mire como se mire.'],
                ['C2', 'comprension', '“Zapis dopuszcza rozbieżne interpretacje”. ¿Qué significa?', ['Solo admite una interpretación', 'Puede admitir interpretaciones divergentes', 'No tiene validez', 'Fue eliminado'], 1, 'Rozbieżne interpretacje son interpretaciones divergentes.'],
                ['C2', 'vocabulario', '¿Qué significa “obalić argument”?', ['Confirmar un argumento', 'Refutar un argumento', 'Resumirlo', 'Publicarlo'], 1, 'Obalić argument significa refutarlo o desmontarlo.'],
                ['C2', 'gramatica', 'Completa: “Gdyby nie jego interwencja, impas ___”.', ['trwałby nadal', 'trwa', 'będzie trwał', 'trwał'], 0, 'La condición irreal actual usa gdyby nie + condicional: trwałby nadal.'],
                ['C2', 'comprension', '“Inicjatywa jest daleka od marginalnej”. ¿Qué se afirma?', ['Es insignificante', 'Tiene un alcance importante', 'Es imposible', 'Fue abandonada'], 1, 'Daleka od marginalnej significa lejos de ser marginal.'],
                ['C2', 'vocabulario', '¿Qué significa “nieunikniony”?', ['Fácil de evitar', 'Inevitable', 'Poco relevante', 'Difícil de traducir'], 1, 'Nieunikniony significa inevitable.'],
            ],
        ];

        foreach ($additionalLanguageQuestions as $language => $languageQuestions) {
            foreach ($languageQuestions as [$level, $category, $question, $options, $correctAnswer, $explanation]) {
                $questions[] = [
                    'language' => $language,
                    'level' => $level,
                    'category' => $category,
                    'question' => $question,
                    'options' => json_encode($options),
                    'correct_answer' => $correctAnswer,
                    'explanation' => $explanation,
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
            }
        }

        foreach ($questions as $question) {
            DB::table('placement_questions')->updateOrInsert(
                [
                    'language' => $question['language'],
                    'level' => $question['level'],
                    'question' => $question['question'],
                ],
                $question
            );
        }
    }
}
