<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlacementQuestionSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [
            [
                'language' => 'ingles',
                'level' => 'A1',
                'category' => 'vocabulario',
                'question' => '¿Qué significa “Hello”?',
                'options' => json_encode([
                    'Adiós',
                    'Hola',
                    'Gracias',
                    'Por favor',
                ]),
                'correct_answer' => 1,
                'explanation' => 'Hello significa Hola.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A1',
                'category' => 'gramatica',
                'question' => 'Completa: “I ___ a student”.',
                'options' => json_encode([
                    'am',
                    'is',
                    'are',
                    'be',
                ]),
                'correct_answer' => 0,
                'explanation' => 'Con I se utiliza am.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A1',
                'category' => 'vocabulario',
                'question' => '¿Qué significa “Good morning”?',
                'options' => json_encode([
                    'Buenas noches',
                    'Buenos días',
                    'Hasta luego',
                    'Bienvenido',
                ]),
                'correct_answer' => 1,
                'explanation' => 'Good morning significa Buenos días.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A1',
                'category' => 'vocabulario',
                'question' => '¿Qué significa “Thank you”?',
                'options' => json_encode(['Hola', 'Gracias', 'Adiós', 'Perdón']),
                'correct_answer' => 1,
                'explanation' => 'Thank you significa Gracias.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A1',
                'category' => 'gramatica',
                'question' => 'Completa: “They ___ friends”.',
                'options' => json_encode(['am', 'is', 'are', 'be']),
                'correct_answer' => 2,
                'explanation' => 'Con They se utiliza are.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A1',
                'category' => 'vocabulario',
                'question' => '¿Qué significa “Book”?',
                'options' => json_encode(['Mesa', 'Libro', 'Silla', 'Puerta']),
                'correct_answer' => 1,
                'explanation' => 'Book significa Libro.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A1',
                'category' => 'gramatica',
                'question' => 'Completa: “This ___ my house”.',
                'options' => json_encode(['am', 'are', 'is', 'be']),
                'correct_answer' => 2,
                'explanation' => 'Con This se utiliza is.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A1',
                'category' => 'vocabulario',
                'question' => '¿Qué significa “Water”?',
                'options' => json_encode(['Agua', 'Comida', 'Leche', 'Pan']),
                'correct_answer' => 0,
                'explanation' => 'Water significa Agua.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A1',
                'category' => 'gramatica',
                'question' => 'Selecciona la opción correcta: “She ___ happy”.',
                'options' => json_encode(['am', 'are', 'is', 'be']),
                'correct_answer' => 2,
                'explanation' => 'Con She se utiliza is.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A1',
                'category' => 'vocabulario',
                'question' => '¿Qué significa “Red”?',
                'options' => json_encode(['Azul', 'Verde', 'Rojo', 'Amarillo']),
                'correct_answer' => 2,
                'explanation' => 'Red significa Rojo.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A1',
                'category' => 'comprension',
                'question' => '“My name is Ana”. ¿Qué significa?',
                'options' => json_encode([
                    'Mi nombre es Ana',
                    'Ana es mi amiga',
                    'Vivo con Ana',
                    'Conozco a Ana',
                ]),
                'correct_answer' => 0,
                'explanation' => 'My name is Ana significa Mi nombre es Ana.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
                ];

        $questions = array_merge($questions, [
            [
                'language' => 'ingles',
                'level' => 'A2',
                'category' => 'gramatica',
                'question' => 'Completa: “She ___ to work by bus”.',
                'options' => json_encode(['go', 'goes', 'going', 'gone']),
                'correct_answer' => 1,
                'explanation' => 'Con She se utiliza goes.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A2',
                'category' => 'gramatica',
                'question' => '¿Cuál es el pasado de “buy”?',
                'options' => json_encode(['Buyed', 'Bought', 'Buying', 'Buys']),
                'correct_answer' => 1,
                'explanation' => 'Bought es el pasado irregular de buy.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A2',
                'category' => 'vocabulario',
                'question' => '¿Qué significa “expensive”?',
                'options' => json_encode(['Barato', 'Rápido', 'Caro', 'Pequeño']),
                'correct_answer' => 2,
                'explanation' => 'Expensive significa caro.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A2',
                'category' => 'gramatica',
                'question' => 'Completa: “I have ___ finished my homework”.',
                'options' => json_encode(['yet', 'already', 'ever', 'never']),
                'correct_answer' => 1,
                'explanation' => 'Already se usa para indicar que algo ya ocurrió.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A2',
                'category' => 'comprension',
                'question' => '“Tom is taller than John”. ¿Qué significa?',
                'options' => json_encode([
                    'Tom es más bajo que John',
                    'Tom es más alto que John',
                    'John es más rápido que Tom',
                    'Tom y John tienen la misma altura',
                ]),
                'correct_answer' => 1,
                'explanation' => 'Taller than significa más alto que.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A2',
                'category' => 'gramatica',
                'question' => 'Completa: “There ___ any milk in the fridge”.',
                'options' => json_encode(['isn’t', 'aren’t', 'don’t', 'doesn’t']),
                'correct_answer' => 0,
                'explanation' => 'Milk es incontable, por eso se usa isn’t.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A2',
                'category' => 'vocabulario',
                'question' => '¿Qué significa “borrow”?',
                'options' => json_encode([
                    'Prestar algo',
                    'Tomar prestado',
                    'Comprar algo',
                    'Romper algo',
                ]),
                'correct_answer' => 1,
                'explanation' => 'Borrow significa tomar prestado.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A2',
                'category' => 'gramatica',
                'question' => 'Completa: “If it rains, I ___ at home”.',
                'options' => json_encode(['stay', 'stayed', 'staying', 'stays']),
                'correct_answer' => 0,
                'explanation' => 'En este caso se usa stay después de I.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A2',
                'category' => 'comprension',
                'question' => '“I have lived here for two years”. ¿Qué significa?',
                'options' => json_encode([
                    'Viví aquí hace dos años',
                    'Vivo aquí desde hace dos años',
                    'Viviré aquí dos años',
                    'No vivo aquí',
                ]),
                'correct_answer' => 1,
                'explanation' => 'La frase indica una acción que comenzó en el pasado y continúa.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'ingles',
                'level' => 'A2',
                'category' => 'gramatica',
                'question' => 'Selecciona la opción correcta: “I ___ watch TV yesterday”.',
                'options' => json_encode([
                    'don’t',
                    'doesn’t',
                    'didn’t',
                    'not',
                ]),
                'correct_answer' => 2,
                'explanation' => 'Para negar en pasado se utiliza didn’t.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

       foreach ($questions as $question) {
    DB::table('placement_questions')->updateOrInsert(
        [
            'language' => $question['language'],
            'level' => $question['level'],
            'question' => $question['question'],
        ],
        $question
    );
}
    }
}
